# Change these first
owner: m0r016 # Your GitHub organization or username, where this repository lives
repo: status # The name of this repository

sites:
  - name: Home
    url: https://www.m0r016.net
  - name: Blog
    url: https://blog.m0r016.net    
  - name: Identity
    url: https://identity.m0r016.net
  - name: slum.cloud
    url: https://slum.cloud
  - name: pleroma
    url: https://wut.m0r016.net
  - name: mstdn.tentere.net
    url: https://mstdn.tentere.net
  - name: File server
    url: https://file.m0r016.net
    
status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.m0r016.net
  # baseUrl: /
  logoUrl: https://avatars.githubusercontent.com/u/44355359
  name: m0r016 network status
  # introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: m0r016 が運営しているサービスのステータスページです。メンテナンス状況などのご確認に活用ください。
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
i18n:
  activeIncidents: "有効なインシデント"
  incidentReport: "インシデントレポート #$NUMBER→"
  activeIncidentSummary: "$DATE にオープン 投稿数 $POSTS"
  incidentTitle: "インシデント #$NUMBER の詳細"
  incidentDetails: "インシデントの詳細"
  incidentFixed: "修正"
  incidentOngoing: "進行中"
  incidentOpenedAt: "オープン"
  incidentClosedAt: "クローズ"
  incidentSubscribe: "アップデートを購読する"
  incidentViewOnGitHub: "GitHubで表示"
  incidentCommentSummary: "投稿日時$DATE 投稿者 $AUTHOR"
  incidentBack: "←すべてのインシデントに戻る"
  pastIncidents: "過去のインシデント"
  pastIncidentsResolved: "$MINUTES 分で解決 投稿数 $POSTS"
  liveStatus: "現在の状態"
  overallUptime: "全体の稼働率: $UPTIME"
  overallUptimeTitle: "全体の稼働率"
  averageResponseTime: "平均応答時間: $TIMEms"
  averageResponseTimeTitle: "平均応答時間"
  sevelDayResponseTime: "7日間の応答時間"
  loading: "読込中"
  navGitHub: "GitHub"
  footer: "このページは[オープンソース]($REPO)で、[Upptime](https://upptime.js.org)を利用しています。"
  rateLimitExceededTitle: "レート制限を超えました"
  rateLimitExceededIntro: "1時間に実行できるリクエストの数を超えたため、このWebサイトに再度アクセスする前に待機する必要があります。 または、GitHubパーソナルアクセストークンを追加して、このWebサイトを引き続き使用することもできます。"
  rateLimitExceededWhatDoesErrorMean: "このエラーはどういう意味ですか？"
  rateLimitExceededErrorMeaning: "このウェブサイトは、GitHub APIを使用して、ウェブサイトのステータスに関するリアルタイムデータにアクセスします。 デフォルトでは、GitHubは各IPアドレスに1時間あたり60リクエストを許可します。"
  rateLimitExceededErrorHowCanFix: "どうすれば修正できますか？"
  rateLimitExceededErrorFix: "さらに1時間待つと、IPアドレスの制限が復元されます。 または、GitHubパーソナルアクセストークンを追加して、1時間あたり5,000件のリクエストを追加することもできます"
  rateLimitExceededGeneratePAT: "パーソナルアクセストークンを生成する方法を学ぶ"
  rateLimitExceededHasSet: "パーソナルアクセストークンセットがあります。"
  rateLimitExceededRemoveToken: "トークンを削除する"
  rateLimitExceededGitHubPAT: "GitHubパーソナルアクセストークン"
  rateLimitExceededCopyPastePAT: "トークンをコピーして貼り付けます"
  rateLimitExceededSaveToken: "トークンを保存"
  errorTitle: "エラーが発生しました"
  errorIntro: "最新のステータスの詳細を取得しようとしてエラーが発生しました。"
  errorText: "しばらくしてからもう一度お試しください。"
  errorHome: "ホームページに移動"
  url: "URL"
  status: "状態"
  history: "履歴"
  uptime: "稼働時間"
  up: "🟩 正常"
  degraded: "🟨 低下"
  down: "🟥 停止"
  responseTimeGraphAlt: "応答時間グラフ"
  ms: "ミリ秒"
  responseTime: "応答時間"
  responseTimeDay: "24時間 応答時間"
  responseTimeWeek: "7日 応答時間"
  responseTimeMonth: "30日 応答時間"
  responseTimeYear: "1年 応答時間"
  uptimeDay: "24時間の稼働時間"
  uptimeWeek: "7日間の稼働時間"
  uptimeMonth: "30日の稼働時間"
  uptimeYear: "1年の稼働時間"
  liveStatusHtmlComment: "<!--live status-->"
  allSystemsOperational: "🟩 すべてのシステムは正常に稼働"
  degradedPerformance: "🟨 パフォーマンスの低下"
  completeOutage: "🟥 完全な停止"
  partialOutage: "🟧 部分的な停止"
